version: '3.8'

services:
  calendar:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - calendar-db:/data/calendar
    
volumes:
  calendar-db:
    name: calendar-container